type Query{
    passwords(isActive : Boolean , username : String , masterPassword : String) : [Password]
    password(uuid : String , username : String , masterPassword : String) : Password
    multiplePasswords(uuids : [String] , username : String) : [Password]
    notifications(type : [String] , username : String) : [Notification]
}
type Password{
    uuid : String
    domain : String
    url : String
    username : String
    email : String
    password : String
    creationDate : String
    updationDate : String
    notes : String
}

type Notification{
    uuid : String
    type : String
    username : String
    description : [String]
}

