spring.application.name=caput draconis
spring.datasource.url=jdbc:postgresql://localhost:5432/caput-draconis
spring.datasource.username=vel
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
logging.level.org.springframework.security=DEBUG
server.servlet.session.timeout=5m
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8080
logging.level.org.springframework.jdbc.datasource.init=DEBUG

spring.batch.jdbc.initialize-schema=ALWAYS
spring.batch.job.enabled=true